# Generated by Django 5.1.4 on 2025-01-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textodapergunta', models.CharField(max_length=200)),
                ('datadepublicacao', models.DateTimeField(verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textodaalternativa', models.CharField(max_length=100)),
                ('votos', models.IntegerField(default=0)),
                ('alternativa1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquete.perguntas')),
            ],
        ),
    ]
